# Generated by Django 4.2 on 2024-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentik_flows', '0026_alter_flow_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLogoutStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentik_flows.stage')),
                ('logout_url_template', models.TextField(blank=True, default='', help_text='URL template for external logout endpoint. Supports placeholders: {user_id}, {username}, {email}, {session_id}, {client_id}', verbose_name='Logout URL Template')),
                ('http_method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('DELETE', 'DELETE')], default='POST', help_text='HTTP method to use for external logout requests', max_length=10, verbose_name='HTTP Method')),
                ('additional_headers', models.JSONField(blank=True, default=dict, help_text='Additional HTTP headers to send with logout requests (JSON format)', verbose_name='Additional Headers')),
                ('request_body_template', models.TextField(blank=True, default='', help_text='Template for request body (for POST requests). Supports same placeholders as URL template. Use JSON format for structured data.', verbose_name='Request Body Template')),
                ('global_logout', models.BooleanField(default=False, help_text='If enabled, will logout from all applications with active tokens. If disabled, only logs out from the current application.', verbose_name='Global Logout')),
                ('request_timeout', models.IntegerField(default=10, help_text='Timeout in seconds for external logout requests', verbose_name='Request Timeout')),
                ('ignore_errors', models.BooleanField(default=True, help_text="If enabled, HTTP errors from external systems won't prevent the logout flow. If disabled, errors will be logged but the logout will continue.", verbose_name='Ignore Errors')),
                ('revoke_tokens', models.BooleanField(default=True, help_text='Whether to revoke OAuth2 access and refresh tokens during logout', verbose_name='Revoke OAuth Tokens')),
            ],
            options={
                'verbose_name': 'External Logout Stage',
                'verbose_name_plural': 'External Logout Stages',
            },
            bases=('authentik_flows.stage',),
        ),
    ]
